flutter_icons:
  android: true
  ios: false
  image_path: "icons/delniit_material_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: icons/delniit_material_icon_foreground.png
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
