name: delniit_dictionary
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: any
  path_provider: any
  sqflite: any
  sqflite_common_ffi: any
  flutter_bloc: ^7.0.0
  provider: any
  context_menus: any
  intl: any
  intersperse: any
  popover: any
  inflection2: any
  dio: any
  fast_immutable_collections: any
  super_sliver_list: any
  draggable_scrollbar:
    git:
      url: https://github.com/thielepaul/flutter-draggable-scrollbar.git
      ref: cfd570035bf393de541d32e9b28808b5d7e602df
  measured_size: any
  visibility_detector: any
  flutter_improved_scrolling: any
  resizable_panel:
    git: https://github.com/Zarainia/flutter-resizable-panel
  delniit_utils:
    git: https://github.com/Zarainia/delniit-utils-dart
  zarainia_utils:
    git: https://github.com/Zarainia/zarainia-utils-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: any
  change_app_package_name: any
  msix: ^3.7.0
  flutter_launcher_icons: any
  flutter_launcher_name: any
  flutter_automation: any

dependency_overrides:
  yaml: ^3.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Times
      fonts:
        - asset: fonts/times.ttf
        - asset: fonts/timesi.ttf
          style: italic
        - asset: fonts/timesbd.ttf
          weight: 700
        - asset: fonts/timesbi.ttf
          style: italic
          weight: 700
    - family: TimesNewDelniit
      fonts:
        - asset: fonts/TimesNewDelniit.ttf

import_sorter:
  comments: false

msix_config:
  display_name: Delniit Dictionary
  publisher_display_name: Valliyv
  identity_name: com.valliyv.delniit-dictionary
  msix_version: 1.0.0.6
  logo_path: icons/delniit_material_icon.png
  capabilities: internetClient
  execution_alias: delniit_dictionary
  build_windows: false
  certificate_path: windows/cert.pfx

flutter_icons:
  android: true
  ios: true
  image_path: "icons/delniit_material_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: icons/delniit_material_icon_foreground.png
  web:
    generate: true
    image_path: "icons/delniit_material_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "icons/delniit_material_icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "icons/delniit_material_icon.png"

flutter_launcher_name:
  name: "Delniit Dictionary"