name: build
run-name: Build flutter app
on:
  push:
    branches:
      - master
jobs:
#  build:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: flutter config --enable-windows-desktop
#      - run: flutter build windows --no-sound-null-safety
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: pwd
    - run: ls
    - run: flutter create --platforms=android
    - run: flutter pub get
    - run: flutter build apk --no-sound-null-safety
    - run: flutter build appbundle --no-sound-null-safety
