name: build
run-name: Build flutter app
on:
  push:
    branches:
      - master
  workflow_call:
jobs:
  build-windows:
    name: Build Windows app
    runs-on: windows-latest
    env:
      BASE64_PFX: ${{ secrets.BASE64_PFX }}
      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter create --platforms=windows,android,ios .
      - name: Run build script
        run: ./release.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: delniit_dictionary.msix
          path: build/windows/runner/Release/delniit_dictionary.msix
  build-android:
    name: Build Android app
    runs-on: ubuntu-latest
    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter create --platforms=android,ios .
      - run: flutter pub get
      - run: flutter pub run change_app_package_name:main com.valliyv.delniit_dictionary
      - run: flutter pub run flutter_launcher_name:main
      - run: flutter pub run flutter_launcher_icons -f android_config.yaml
      - run: echo $KEY_JKS > android/key.jks
      - run: flutter build apk --release --no-sound-null-safety
      - uses: actions/upload-artifact@v3
        with:
          name: delniit_dictionary.apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - run: flutter build appbundle --release --no-sound-null-safety
      - uses: actions/upload-artifact@v3
        with:
          name: delniit_dictionary.aab
          path: build/app/outputs/bundle/release/app-release.aab
