name: build
run-name: Build flutter app
on:
  push:
    tags:
jobs:
  build:
    name: Build Flutter app
    uses: ./.github/workflows/build.yml
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Download MSIX
        uses: actions/download-artifact@v3
        with:
          name: delniit_dictionary.msix
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: delniit_dictionary.apk
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload MSIX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./delniit_dictionary.msix
          asset_name: delniit_dictionary.msix
          asset_content_type: application/msix
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./delniit_dictionary.apk
          asset_name: delniit_dictionary.apk
          asset_content_type: application/apk